# Generated by Django 2.2.5 on 2021-12-30 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_email_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_address',
            field=models.IntegerField(blank=True, null=True, verbose_name='默认地址'),
        ),
    ]
